package ibmro.common.androidCommon




//intent extra
const val KEY_TITLE_SECTION = "KEY_TITLE_SECTION_VIEW_MORE"
const val KEY_TITLE_ITEM = "KEY_TITLE_ITEM"
const val KEY_ID_QUESTION = "KEY_ID_QUESTION"
const val KEY_QUESTION_VIEW = "KEY_QUESTION_VIEW"
const val KEY_CANDIDATE_ID= "KEY_CANDIDATE_ID"
const val KEY_CANDIDATE_VIEW = "KEY_CANDIDATE_VIEW"
const val KEY_PROFILE="KEY_PROFILE"
const val KEY_COMPLETED_PROFILE_STEP="KEY_COMPLETED_PROFILE_STEP"

